# Generated by Django 5.2.6 on 2025-10-24 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True, verbose_name='ID do Pedido')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID do Usuário')),
                ('user_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto Bancário')], max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('declined', 'Recusado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, verbose_name='Nome no Cartão')),
                ('card_number_last4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Bandeira')),
                ('installments', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcelas')),
                ('pix_key', models.CharField(blank=True, max_length=255, verbose_name='Chave PIX')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('pix_code', models.TextField(blank=True, verbose_name='Código PIX Copia e Cola')),
                ('boleto_barcode', models.CharField(blank=True, max_length=100, verbose_name='Código de Barras')),
                ('boleto_url', models.URLField(blank=True, verbose_name='URL do Boleto')),
                ('boleto_due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID da Transação no Gateway')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta do Gateway')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Reembolsado em')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='payments_order_i_b32b33_idx'), models.Index(fields=['user_id'], name='payments_user_id_7f3925_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('declined', 'Recusado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Status Anterior')),
                ('to_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('declined', 'Recusado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Novo Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('changed_by', models.IntegerField(blank=True, null=True, verbose_name='Alterado por (User ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Mudança')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pagamento_service.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Pagamento',
                'verbose_name_plural': 'Histórico de Status dos Pagamentos',
                'db_table': 'payment_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Reembolso')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, verbose_name='ID do Reembolso no Gateway')),
                ('requested_by', models.IntegerField(verbose_name='Solicitado por (User ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pagamento_service.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
