# Generated by Django 5.2.6 on 2025-10-25 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID do Usuário')),
                ('email_account', models.BooleanField(default=True, verbose_name='Email - Conta')),
                ('email_order', models.BooleanField(default=True, verbose_name='Email - Pedidos')),
                ('email_payment', models.BooleanField(default=True, verbose_name='Email - Pagamentos')),
                ('email_promotion', models.BooleanField(default=True, verbose_name='Email - Promoções')),
                ('sms_order', models.BooleanField(default=False, verbose_name='SMS - Pedidos')),
                ('sms_payment', models.BooleanField(default=False, verbose_name='SMS - Pagamentos')),
                ('push_order', models.BooleanField(default=True, verbose_name='Push - Pedidos')),
                ('push_payment', models.BooleanField(default=True, verbose_name='Push - Pagamentos')),
                ('push_promotion', models.BooleanField(default=True, verbose_name='Push - Promoções')),
                ('in_app_all', models.BooleanField(default=True, verbose_name='Notificações no App')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome identificador do template', max_length=100, unique=True, verbose_name='Nome')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notificação no App')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('account', 'Conta'), ('order', 'Pedido'), ('payment', 'Pagamento'), ('promotion', 'Promoção'), ('system', 'Sistema')], max_length=20, verbose_name='Categoria')),
                ('subject', models.CharField(help_text='Para emails. Suporta variáveis: {{var}}', max_length=255, verbose_name='Assunto')),
                ('body', models.TextField(help_text='Mensagem. Suporta variáveis: {{var}}', verbose_name='Corpo')),
                ('html_body', models.TextField(blank=True, help_text='Para emails HTML. Suporta variáveis: {{var}}', verbose_name='Corpo HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID do Usuário')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do Usuário')),
                ('user_phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone do Usuário')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notificação no App')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('account', 'Conta'), ('order', 'Pedido'), ('payment', 'Pagamento'), ('promotion', 'Promoção'), ('system', 'Sistema')], max_length=20, verbose_name='Categoria')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('html_content', models.TextField(blank=True, help_text='Para emails HTML', verbose_name='Conteúdo HTML')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dados extras como order_id, payment_id, etc.', verbose_name='Dados Adicionais')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de Ação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('read', 'Lido')], default='pending', max_length=20, verbose_name='Status')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['category'], name='notificatio_categor_c83784_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
