# Generated by Django 5.2.6 on 2025-10-26 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('produto_id', models.IntegerField()),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avaliacao_produto',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['produto_id', '-nota'], name='avaliacao_p_produto_4cfd49_idx'), models.Index(fields=['usuario_id'], name='avaliacao_p_usuario_33f60a_idx')],
                'unique_together': {('usuario_id', 'produto_id')},
            },
        ),
        migrations.CreateModel(
            name='InteracaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('produto_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('VIEW', 'Visualização'), ('CART', 'Adição ao Carrinho'), ('PURCHASE', 'Compra'), ('FAVORITE', 'Favorito')], max_length=10)),
                ('peso', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interacao_produto',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario_id', 'tipo'], name='interacao_p_usuario_746121_idx'), models.Index(fields=['produto_id', 'tipo'], name='interacao_p_produto_5404bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('tipo_recomendacao', models.CharField(max_length=50)),
                ('produtos_ids', models.JSONField()),
                ('score', models.FloatField(default=0.0)),
                ('gerado_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
            ],
            options={
                'db_table': 'recomendacao_gerada',
                'ordering': ['-gerado_em'],
                'indexes': [models.Index(fields=['usuario_id', 'tipo_recomendacao'], name='recomendaca_usuario_ffb358_idx'), models.Index(fields=['expira_em'], name='recomendaca_expira__9f9bb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('produto_id', models.IntegerField()),
                ('visualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visualizacao_produto',
                'ordering': ['-visualizado_em'],
                'indexes': [models.Index(fields=['usuario_id', '-visualizado_em'], name='visualizaca_usuario_c3d006_idx'), models.Index(fields=['produto_id'], name='visualizaca_produto_30b3fa_idx')],
            },
        ),
    ]
