# Generated by Django 5.2.6 on 2025-11-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvaliacaoProduto',
        ),
        migrations.DeleteModel(
            name='InteracaoProduto',
        ),
        migrations.DeleteModel(
            name='RecomendacaoGerada',
        ),
        migrations.DeleteModel(
            name='VisualizacaoProduto',
        ),
    ]
