# Generated by Django 5.2.6 on 2025-10-24 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='ID do Usuário')),
                ('user_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('user_phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone do Cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frete')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('shipping_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('shipping_number', models.CharField(max_length=20, verbose_name='Número')),
                ('shipping_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('shipping_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('shipping_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('shipping_zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='orders_user_id_4e08b8_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(verbose_name='ID do Produto')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('product_sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('product_image', models.URLField(blank=True, verbose_name='Imagem do Produto')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestao_pedidos_service.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Status Anterior')),
                ('to_status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Novo Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('changed_by', models.IntegerField(blank=True, null=True, verbose_name='Alterado por (User ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Mudança')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='gestao_pedidos_service.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Histórico de Status',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
